---
title: "Clustering"
author: "Chris Lin"
date: "4/23/2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(Seurat)
library(MAST)
library(ggplot2)
```


```{r 1}
cells <- readRDS("/projectnb/bf528/users/group3/project4/mydata.rds")
```



```{r 2}
cells.markers <- FindAllMarkers(cells, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
cells.markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_logFC)
top_markers <- cells.markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_logFC)
write.csv(top_markers,"top_DE_genes.csv")


```


```{r 3}
database <- read.table('/projectnb/bf528/users/group3/project4/PanglaoDB_markers_27_Mar_2020.tsv', sep = '\t', header=TRUE, stringsAsFactors = FALSE)
cells.markers$cell_type <- NA
cells.markers$cannonical <- NA
cells.markers$ubiquitous_index <- NA
cells.markers$specificity <- NA
for (row in 1:nrow(cells.markers)) {
  gene <- cells.markers[row, "gene"]
  if (gene %in% database$official.gene.symbol)
    indicies <- which(database$official.gene.symbol == gene)
    cells.markers$cell_type[row] <- database[indicies[1], 3]
    cells.markers$cannonical[row] <- database[indicies[1], 8]
    cells.markers$ubiquitous_index[row] <- database[indicies[1], 5]
    cells.markers$specificity[row] <- database[indicies[1], 13]

  
}
cells.markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_logFC)

```


```{r 3}
new.cluster.ids <- c('Alpha', 'Alpha', 'Beta', 'Delta', 'Hepatic stellate', 'Ductal', 'Acinar', 'Gamma', 'Endothelial', 'Acinar')
names(new.cluster.ids) <- levels(cells)
cells <- RenameIdents(cells, new.cluster.ids)
DimPlot(cells, reduction = "umap", label = TRUE, pt.size = 0.5) + NoLegend()

```


```{r fig.height = 10, fig.width = 15}

top10 <- cells.markers %>% group_by(cluster) %>% top_n(n = 5, wt = avg_logFC)
DoHeatmap(cells, features = top10$gene, disp.min = -2.5, disp.max = 2.5, size = 5, angle = 90)  + theme(axis.text.y = element_text(size = 5)) + theme(axis.title.x = element_text(size = 2))

```

```{r }
novel_markers <- cells.markers %>% group_by(cluster) %>% arrange(desc(avg_logFC), .by_group = TRUE) 
novel_markers <- novel_markers[ which(novel_markers$p_val_adj < 0.05 & novel_markers$specificity < 0.1 & novel_markers$avg_logFC > 0.75),]
novel_markers <- novel_markers %>% group_by(cluster) %>% top_n(n = 5, wt = avg_logFC)

```
